kind: pipeline
type: kubernetes
name: default

steps:
  - name: build-push
    image: adamhancock/dind
    volumes:
      - name: dockersock
        path: /run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - sleep 5 #
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - cd docker-custom
      - docker buildx create --use --name build --node build --driver-opt network=host
      - docker buildx build . -f Dockerfile.custom -t $DOCKER_USER/node-red --push --platform linux/amd64

  - name: deliver
    image: adamhancock/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: DEV_K8S_HOST
      kubernetes_cert:
        from_secret: DEV_K8S_CERT
      kubernetes_token:
        from_secret: DEV_K8S_TOKEN
    commands:
      - kubectl rollout restart deploy node-red -n node-red
      # - docker push $DOCKER_USER/node-red
volumes:
  - name: dockersock
    host:
      path: /run
