kind: pipeline
type: kubernetes
name: default

steps:
  - name: build-push
    image: adamhancock/dind
    volumes:
      - name: dockersock
        path: /run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - sleep 5 #
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - cd docker-custom
      - docker buildx create --use --name build --node build --driver-opt network=host
      - docker buildx build . -f Dockerfile.custom -t $DOCKER_USER/node-red --push --platform linux/amd64,linux/arm
      # - docker push $DOCKER_USER/node-red
volumes:
  - name: dockersock
    host:
      path: /run
